server:
  port: 9191  # Your client app port
  error:
       include-stacktrace: never

spring:
  application:
    name: owner-service  # Logical service name registered with Eureka
  security:
       filter:
        dispatcher-types: REQUEST,ASYNC

  datasource:
    url: jdbc:mysql://localhost:3306/microserviceDb?useSSL=false&serverTimezone=UTC
    username: root
    password: Root@007
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # or create, validate etc.
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server URL
    register-with-eureka: true   # Register this client with Eureka server
    fetch-registry: true         # Fetch registry info from Eureka server

  instance:
    hostname: localhost
    prefer-ip-address: true  # Register using IP address instead of hostname (optional)

management:
  endpoints:
    web:
      exposure:
        include: info, health  # Expose only /info and /health
  endpoint:
    health:
      show-details: always  # Optional: show full health details
  info:
    env:
      enabled: true  # Optional: include environment info if needed

info:
  app:
    name: Owner Service
    description: Service for managing owners
    version: 1.0.0
  jwt:
  secret: "bXktd2hvcHBlci1zZWNyZXQtc2lnbmluZy1rZXktMzJieXRlc0Jhc2U2NA==" # base64; use 256-bit+
  expiration-minutes: 60